import { useAppStore } from '@/store/useAppStore';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Switch } from '@/components/ui/switch';
import { Label } from '@/components/ui/label';
import { Separator } from '@/components/ui/separator';
import { Info } from 'lucide-react';
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from '@/components/ui/tooltip';

export default function CopilotSettings() {
  const settings = useAppStore((state) => state.aiSponsorChat?.settings);
  const updateCopilotSettings = useAppStore((state) => state.updateCopilotSettings);

  if (!settings) {
    return null;
  }

  const handleToggle = (key: keyof typeof settings, value: boolean) => {
    updateCopilotSettings({ [key]: value });
  };

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center gap-2">
          <CardTitle>Recovery Copilot Settings</CardTitle>
          <TooltipProvider>
            <Tooltip>
              <TooltipTrigger asChild>
                <Info className="h-4 w-4 text-muted-foreground" />
              </TooltipTrigger>
              <TooltipContent>
                <p className="max-w-xs">
                  Control what data Recovery Copilot uses to provide personalized support.
                  Your data stays private and is only used to improve your experience.
                </p>
              </TooltipContent>
            </Tooltip>
          </TooltipProvider>
        </div>
        <CardDescription>
          Choose what information to include when chatting with Recovery Copilot
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <div className="space-y-0.5">
              <Label htmlFor="include-step-work">Include Step Work</Label>
              <p className="text-sm text-muted-foreground">
                Recent step entries will be included for context
              </p>
            </div>
            <Switch
              id="include-step-work"
              checked={settings.includeStepWork}
              onCheckedChange={(checked) => handleToggle('includeStepWork', checked)}
            />
          </div>

          <Separator />

          <div className="flex items-center justify-between">
            <div className="space-y-0.5">
              <Label htmlFor="include-journals">Include Journal Entries</Label>
              <p className="text-sm text-muted-foreground">
                Recent journal entries will be included for context
              </p>
            </div>
            <Switch
              id="include-journals"
              checked={settings.includeJournals}
              onCheckedChange={(checked) => handleToggle('includeJournals', checked)}
            />
          </div>

          <Separator />

          <div className="flex items-center justify-between">
            <div className="space-y-0.5">
              <Label htmlFor="include-scenes">Include Recovery Scenes</Label>
              <p className="text-sm text-muted-foreground">
                Active recovery scenes will be included for context
              </p>
            </div>
            <Switch
              id="include-scenes"
              checked={settings.includeScenes}
              onCheckedChange={(checked) => handleToggle('includeScenes', checked)}
            />
          </div>

          <Separator />

          <div className="flex items-center justify-between">
            <div className="space-y-0.5">
              <Label htmlFor="include-daily-cards">Include Daily Check-ins</Label>
              <p className="text-sm text-muted-foreground">
                Mood and cravings trends from daily cards will be included
              </p>
            </div>
            <Switch
              id="include-daily-cards"
              checked={settings.includeDailyCards}
              onCheckedChange={(checked) => handleToggle('includeDailyCards', checked)}
            />
          </div>

          <Separator />

          <div className="flex items-center justify-between">
            <div className="space-y-0.5">
              <Label htmlFor="auto-generate-digest">Auto-Generate Weekly Digest</Label>
              <p className="text-sm text-muted-foreground">
                Automatically generate a weekly summary of your recovery journey
              </p>
            </div>
            <Switch
              id="auto-generate-digest"
              checked={settings.autoGenerateDigest}
              onCheckedChange={(checked) => handleToggle('autoGenerateDigest', checked)}
            />
          </div>
        </div>

        <div className="mt-6 p-4 bg-muted/50 rounded-lg">
          <p className="text-sm text-muted-foreground">
            <strong>Privacy Note:</strong> Your data is processed locally when possible.
            Only summaries are sent to the AI service, never full entries. You can change
            these settings anytime.
          </p>
        </div>
      </CardContent>
    </Card>
  );
}

